### ISSUE TITLE
Построить диаграмму классов ИС для ранее нормализованной БД, в соответствии с SOLID

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/Korostylev_A#1]
Студент(ка): Коростылев Артем Владимирович
Выполнить до 16.10.2020 18:00

**Comment by artemchiks** [comment]
![Снимок](https://user-images.githubusercontent.com/72761930/96553176-72dae880-12bd-11eb-9a35-dc81943bb7fd.PNG)

**Comment by bespalova-m-a** [comment]
При чём тут компоненты и элементы БД?

**Comment by bespalova-m-a** [comment]
Стрелки сделать ровные и нормальные. Компоненты разложить на классы. Элемент из базы данных убрать или показать её классом

**Comment by bespalova-m-a** [comment]
Диаграмму классов переделать

**Comment by artemchiks** [comment]
![Диграмма](https://user-images.githubusercontent.com/72761930/96561046-bfc3bc80-12c7-11eb-83de-dbb0c20ca493.PNG)

**Comment by artemchiks** [comment]
![Снимок](https://user-images.githubusercontent.com/72761930/97599244-cfa27580-1a18-11eb-9df8-d5b48b96d56e.PNG)

**Comment by artemchiks** [comment]
![image](https://user-images.githubusercontent.com/72761930/97879293-dc80db00-1d30-11eb-9cc6-6df272543cc5.png)

**Comment by bespalova-m-a** [comment]
Работа принята, оценка отлично
