### ISSUE TITLE
Создать скетч GUI ПП под ранее созданную БД (магазин канцтоваров). Выполнить до 23.10.2020 18:00

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/Korostylev_A#2]

**Comment by artemchiks** [comment]
![image](https://user-images.githubusercontent.com/72761930/96562748-c94e2400-12c9-11eb-99fe-429ccc798028.png)

**Comment by artemchiks** [comment]
![image](https://user-images.githubusercontent.com/72761930/96562773-d4a14f80-12c9-11eb-8173-ee40a364414f.png)

**Comment by artemchiks** [comment]
![Uploading image.png…]()

**Comment by bespalova-m-a** [comment]
Работа принята, оценка - отлично
