### ISSUE TITLE
Разработка приложения канцтоваров с использованием Windows Forms в среде MS Visual Studio на языке C#. Выполнить до 30.11.2020

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/Korostylev_A#5]
Студент(ка): Коростылев Артем Владимирович

**Comment by bespalova-m-a** [comment]
Разработать приложение в соответствии:
- [ ] архитектурой программного продукта (SOLID)
- [ ]  макетом GUI
- [ ]  базой данных

**Comment by artemchiks** [comment]
#7

**Comment by bespalova-m-a** [comment]
Работа принята
