### ISSUE TITLE
Разработка приложения канцтоваров с использованием WPF формы в среде MS Visual Studio на языке C#. Выполнить до 14.12.2020

### ISSUE THREAD

**Issue by bespalova-m-a** [IDC-02-01/Korostylev_A#6]
Студент(ка): Коростылев Артем Владимирович

**Comment by bespalova-m-a** [comment]
Разработать приложение в соответствии:
- [ ] архитектурой программного продукта (SOLID)
- [ ] макетом GUI
- [ ] базой данных

**Comment by artemchiks** [comment]
![image](https://user-images.githubusercontent.com/72761930/101455619-eacfa180-3943-11eb-9167-c77a08046c8d.png)

**Comment by artemchiks** [comment]
https://github.com/artemchiks/Wpfworm

**Comment by bespalova-m-a** [comment]
работа принята
